FROM nixyslab/nxs-backup-bin AS bin

FROM debian:trixie-slim

RUN apt update \
    && apt install -yq --no-install-recommends \
      wget \
      lsb-release \
      gnupg \
      ca-certificates \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/postgresql-archive-keyring.gpg] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt update \
    && apt install -yq --no-install-recommends \
      postgresql-client-17 \
    && psql --version \
    && apt remove -y wget gnupg lsb-release \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

COPY --from=bin /nxs-backup /usr/local/bin/nxs-backup

CMD nxs-backup start