#!/bin/bash

# waiting for go-multierror removal (has PR, not merged yet)
#go get github.com/jlaffaye/ftp@6602e98
#go mod edit -replace github.com/jlaffaye/ftp@6602e98=./lib/ftp

# project abandoned, has critical panic fix PR, not merged
#go get github.com/hirochachacha/go-smb2
#go mod edit -replace github.com/hirochachacha/go-smb2=./lib/go-smb2

#go get github.com/vmware/go-nfs-client/nfs
#go get github.com/vmware/go-nfs-client/nfs/rpc
#go get github.com/pkg/sftp

#go get github.com/minio/minio-go/v7
