FROM nixyslab/nxs-backup-bin AS bin

FROM debian:trixie-slim

RUN apt update \
    && apt install -yq --no-install-recommends \
      wget \
      gnupg \
      lsb-release \
      ca-certificates \
    && wget -qO - https://www.mongodb.org/static/pgp/server-8.0.asc | gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg \
    && echo "deb [signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-8.0.list \
    && apt update \
    && apt install -yq --no-install-recommends mongodb-database-tools \
    && apt remove -y wget gnupg lsb-release \
    && apt autoremove -y \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=bin /nxs-backup /usr/local/bin/nxs-backup

CMD nxs-backup start