services:
  nxs-backup:
    image: nixyslab/nxs-backup:latest
    container_name: nxs-backup
    command:
    - nxs-backup
    - -c
    - /nxs-backup.yml
    - start
    - all
    volumes:
    - type: bind
      source: ./backup
      target: /var/nxs-backup/dump_tmp
    configs:
    - nxs-backup.yml
configs:
  nxs-backup.yml:
    file: ./nxs-backup.yml
